### ISSUE TITLE
error for running mergeUmi

### ISSUE THREAD

**Issue by lixin4306ren** [csf-ngs/surecellumi#1]
Thank you for providing this extractor. 
My python version is 3.5.2. I instlled the package and then tried to run merge.sh and got following error:

```
2017-08-31 03:40:48,358 - root - INFO - starting extracting umis
2017-08-31 03:40:48,359 - root - INFO - extracting umis with: TAGCCATCGCATTGC TACCTCTGAGCTGAA TAGCCATCGCATTGCNNNNNNTACCTCTGAGCTGAA
Traceback (most recent call last):
  File "/home/others/xli/bin/mergeUmi", line 6, in <module>
    exec(compile(open(__file__).read(), __file__, 'exec'))
  File "/home/others/xli/soft/src/surecellumi/bin/mergeUmi", line 28, in <module>
    mergeUmiFiles(args.r1, args.r2, args.outfq, args.outextract, args.outbc, args.outprime5, ll1, ll2, llinker)
  File "/home/others/xli/soft/src/surecellumi/surecellumi/mergefq.py", line 26, in mergeUmiFiles
    ignore = f1.next()
AttributeError: '_io.TextIOWrapper' object has no attribute 'next'

```

**Comment by idot** [comment]
Thank you for trying. I have disabled python 3 for this package. The python 2 version compiles and passes all tests.
